steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/learning-261705/html-server-image:v1:latest || exit 0'
  ]
  #step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/learning-261705/html-server-image:v1:$BRANCH_NAME-$COMMIT_SHA',
   '-t', 
   'gcr.io/learning-261705/html-server-image:v1:latest',
   '.'
  ]

