steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/learning-261705/html-server-image:v1:latest || exit 0'
  ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/learning-261705/html-server-image:v1:$BRANCH_NAME-$COMMIT_SHA',
   '-t', 
   'gcr.io/learning-261705/html-server-image:v1:latest',
   '.'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'html-server-image:v1', 
   'html-server-image:v1=gcr.io/learning-261705/html-server-image:v1:$BRANCH_NAME-$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
# push images to Google Container Registry with branch
images: [
   'gcr.io/learning-261705/html-server-image:v1:$BRANCH_NAME-$COMMIT_SHA',
   'gcr.io/learning-261705/html-server-image:v1:latest'
  ]
